import { Car } from "./types/Car";

const dummyCars: Car[] = [
  {
    id: 1,
    make: "Tesla",
    model: "Model 3",
    year: 2021,
    pricePerKm: 3.5,
    location: "Copenhagen",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1449481/car_1754827603.jpeg?w=768&h=511&fit=crop&auto=format%2Ccompress&dpr=1",
    owner: {
      id: 1,
      name: "Mette Hansen",
      avatarUrl: "https://i.pravatar.cc/150?img=1",
      rating: 4.8,
      numberOfReviews: 24,
    },
    carType: "Medium",
    fuelType: "Electric",
    transmission: "Automatic",
    seats: 5,
    bookings: [
      { id: 101, from: new Date("2025-10-10"), to: new Date("2025-10-12") },
      { id: 102, from: new Date("2025-10-13"), to: new Date("2025-10-14") }
    ],
    availability: [
      { id: 1, from: new Date("2025-10-1"), to: new Date("2025-10-22") },
    ]
  },
  {
    id: 2,
    make: "Volkswagen",
    model: "Golf",
    year: 2019,
    pricePerKm: 2.0,
    location: "Aarhus",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1376551/car_1751467809.jpeg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 2,
      name: "Lars Nielsen",
      avatarUrl: "https://i.pravatar.cc/150?img=2",
      rating: 4.5,
      numberOfReviews: 15,
    },
    carType: "Medium",
    fuelType: "Petrol",
    transmission: "Manual",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 3,
    make: "Toyota",
    model: "Yaris",
    year: 2020,
    pricePerKm: 2.2,
    location: "Odense",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1320847/car_1749145225.jpeg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 3,
      name: "Anne Sørensen",
      avatarUrl: "https://i.pravatar.cc/150?img=3",
      rating: 4.7,
      numberOfReviews: 18,
    },
    carType: "Micro Car",
    fuelType: "Hybrid",
    transmission: "Automatic",
    seats: 5,
    bookings: [
      { id: 102, from: new Date("2025-11-01"), to: new Date("2025-11-05") },
    ],
    availability: true,
  },
  {
    id: 4,
    make: "Ford",
    model: "Kuga",
    year: 2018,
    pricePerKm: 3.0,
    location: "Aalborg",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1401378/car_1752665683.jpg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 4,
      name: "Jens Pedersen",
      avatarUrl: "https://i.pravatar.cc/150?img=4",
      rating: 4.2,
      numberOfReviews: 12,
    },
    carType: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    seats: 5,
    bookings: [],
    availability: false,
  },
  {
    id: 5,
    make: "Mercedes-Benz",
    model: "Vito",
    year: 2017,
    pricePerKm: 4.0,
    location: "Roskilde",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1284712/car_1747330340.jpeg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 5,
      name: "Kirsten Møller",
      avatarUrl: "https://i.pravatar.cc/150?img=5",
      rating: 4.9,
      numberOfReviews: 30,
    },
    carType: "Van",
    fuelType: "Diesel",
    transmission: "Manual",
    seats: 8,
    bookings: [],
    availability: true,
  },
  {
    id: 6,
    make: "Nissan",
    model: "Leaf",
    year: 2022,
    pricePerKm: 3.8,
    location: "Fredericia",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/969240/car_5395075f-95e5-4a09-ac4e-44d065fcc429.jpg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 6,
      name: "Søren Jensen",
      avatarUrl: "https://i.pravatar.cc/150?img=6",
      rating: 4.6,
      numberOfReviews: 20,
    },
    carType: "Medium",
    fuelType: "Electric",
    transmission: "Automatic",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 7,
    make: "Kia",
    model: "Niro",
    year: 2021,
    pricePerKm: 3.4,
    location: "Esbjerg",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/626922/car_1659636751.jpg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 7,
      name: "Sofie Kristensen",
      avatarUrl: "https://i.pravatar.cc/150?img=7",
      rating: 4.3,
      numberOfReviews: 14,
    },
    carType: "SUV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    seats: 5,
    bookings: [
      { id: 103, from: new Date("2025-12-01"), to: new Date("2025-12-10") },
    ],
    availability: true,
  },
  {
    id: 8,
    make: "Volkswagen",
    model: "ID.3",
    year: 2023,
    pricePerKm: 4.2,
    location: "Herning",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1546864/car_1758880684.jpeg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 8,
      name: "Mads Kristoffersen",
      avatarUrl: "https://i.pravatar.cc/150?img=8",
      rating: 4.7,
      numberOfReviews: 25,
    },
    carType: "Medium",
    fuelType: "Electric",
    transmission: "Automatic",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 9,
    make: "BMW",
    model: "X5",
    year: 2020,
    pricePerKm: 5.0,
    location: "Vejle",
    imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2025-bmw-x5-xdrive40i-108-6824bd45baa30.jpg?crop=0.641xw:0.540xh;0.131xw,0.315xh&resize=1200:*",
    owner: {
      id: 9,
      name: "Henrik Rasmussen",
      avatarUrl: "https://i.pravatar.cc/150?img=9",
      rating: 4.4,
      numberOfReviews: 17,
    },
    carType: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 10,
    make: "Hyundai",
    model: "i10",
    year: 2018,
    pricePerKm: 1.8,
    location: "Horsens",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1237336/car_1744634275.jpg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 10,
      name: "Camilla Olsen",
      avatarUrl: "https://i.pravatar.cc/150?img=10",
      rating: 4.1,
      numberOfReviews: 11,
    },
    carType: "Micro Car",
    fuelType: "Petrol",
    transmission: "Manual",
    seats: 4,
    bookings: [],
    availability: true,
  },
  {
    id: 11,
    make: "Ford",
    model: "Transit",
    year: 2019,
    pricePerKm: 4.5,
    location: "Randers",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/990756/car_1719565212.jpg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 11,
      name: "Rikke Larsen",
      avatarUrl: "https://i.pravatar.cc/150?img=11",
      rating: 4.0,
      numberOfReviews: 8,
    },
    carType: "Van",
    fuelType: "Diesel",
    transmission: "Manual",
    seats: 3,
    bookings: [],
    availability: false,
  },
  {
    id: 12,
    make: "Mercedes-Benz",
    model: "Sprinter",
    year: 2022,
    pricePerKm: 5.5,
    location: "Kolding",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1384413/car_1751886260.jpeg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 12,
      name: "Thomas Holm",
      avatarUrl: "https://i.pravatar.cc/150?img=12",
      rating: 4.8,
      numberOfReviews: 28,
    },
    carType: "Mini Bus",
    fuelType: "Diesel",
    transmission: "Automatic",
    seats: 12,
    bookings: [],
    availability: true,
  },
  {
    id: 13,
    make: "Volvo",
    model: "XC40",
    year: 2021,
    pricePerKm: 4.8,
    location: "Silkeborg",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1285984/car_1747404780.jpeg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 13,
      name: "Birgit Pedersen",
      avatarUrl: "https://i.pravatar.cc/150?img=13",
      rating: 4.6,
      numberOfReviews: 19,
    },
    carType: "SUV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 14,
    make: "Skoda",
    model: "Octavia",
    year: 2019,
    pricePerKm: 3.1,
    location: "Hjørring",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1237327/car_1744633800.jpg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 14,
      name: "Lene Sørensen",
      avatarUrl: "https://i.pravatar.cc/150?img=14",
      rating: 4.3,
      numberOfReviews: 13,
    },
    carType: "Medium",
    fuelType: "Petrol",
    transmission: "Manual",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 15,
    make: "Peugeot",
    model: "208",
    year: 2022,
    pricePerKm: 3.0,
    location: "Holstebro",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/729401/car_1679651062.png?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 15,
      name: "Lukas Mortensen",
      avatarUrl: "https://i.pravatar.cc/150?img=15",
      rating: 4.2,
      numberOfReviews: 10,
    },
    carType: "Micro Car",
    fuelType: "Electric",
    transmission: "Automatic",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 16,
    make: "Audi",
    model: "Q5",
    year: 2020,
    pricePerKm: 4.9,
    location: "Næstved",
    imageUrl: "https://chileautos.pxcrush.net/cars/dealer/ukslln5x3jv8h0nl01f77p9b.jpg?pxc_method=fitfill&pxc_bgtype=self&height=725&width=1087",
    owner: {
      id: 16,
      name: "Peter Jensen",
      avatarUrl: "https://i.pravatar.cc/150?img=16",
      rating: 4.5,
      numberOfReviews: 21,
    },
    carType: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 17,
    make: "Renault",
    model: "Clio",
    year: 2019,
    pricePerKm: 2.3,
    location: "Frederikshavn",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1041298/car_1725029882.jpeg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 17,
      name: "Camilla Hansen",
      avatarUrl: "https://i.pravatar.cc/150?img=17",
      rating: 4.0,
      numberOfReviews: 9,
    },
    carType: "Micro Car",
    fuelType: "Petrol",
    transmission: "Manual",
    seats: 5,
    bookings: [],
    availability: false,
  },
  {
    id: 18,
    make: "Mazda",
    model: "CX-5",
    year: 2021,
    pricePerKm: 4.7,
    location: "Nyborg",
    imageUrl: "https://d147al5y0i1rb.cloudfront.net/uploads/car_picture/image/1419726/car_1753469821.jpg?ixlib=rails-4.3.1&auto=format%2Ccompress&fit=crop&h=372&w=560&dpr=1",
    owner: {
      id: 18,
      name: "Mia Larsen",
      avatarUrl: "https://i.pravatar.cc/150?img=18",
      rating: 4.4,
      numberOfReviews: 16,
    },
    carType: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 19,
    make: "Hyundai",
    model: "Tucson",
    year: 2022,
    pricePerKm: 4.6,
    location: "Sønderborg",
    imageUrl: "https://images.prismic.io/carwow/aA-N8_IqRLdaBrHs_HyundaiTucson2025exteriorfrontthreequarterviewdriving.jpg?auto=format&cs=tinysrgb&fit=max&q=60",
    owner: {
      id: 19,
      name: "Christian Poulsen",
      avatarUrl: "https://i.pravatar.cc/150?img=19",
      rating: 4.8,
      numberOfReviews: 22,
    },
    carType: "SUV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    seats: 5,
    bookings: [],
    availability: true,
  },
  {
    id: 20,
    make: "Peugeot",
    model: "Traveller",
    year: 2021,
    pricePerKm: 5.2,
    location: "Viborg",
    imageUrl: "https://ireland.apollo.olxcdn.com/v1/files/egr9qlw0cx2q-OTOMOTOPL/image;s=640x480",
    owner: {
      id: 20,
      name: "Lone Mortensen",
      avatarUrl: "https://i.pravatar.cc/150?img=20",
      rating: 4.9,
      numberOfReviews: 27,
    },
    carType: "Mini Bus",
    fuelType: "Diesel",
    transmission: "Automatic",
    seats: 9,
    bookings: [],
    availability: true,
  },
];


export default dummyCars;